name: postgress_table_form_example
description: "Example app for PostgreSQL Table Form package"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  postgress_table_form:
    path: ../
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 